// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq0TJ9VZR1L4iNRnfeDAzgpDR4GLfXxLg',
    appId: '1:836056728153:web:125f3c173bd4ce86bd6748',
    messagingSenderId: '836056728153',
    projectId: 'wisaga-918b7',
    authDomain: 'wisaga-918b7.firebaseapp.com',
    databaseURL: 'https://wisaga-918b7-default-rtdb.firebaseio.com',
    storageBucket: 'wisaga-918b7.appspot.com',
    measurementId: 'G-3D9XE5BCGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9xfT0mREPCVLdUT0D1bSMvIhGHm-pUb4',
    appId: '1:836056728153:android:6347c410d0c14edbbd6748',
    messagingSenderId: '836056728153',
    projectId: 'wisaga-918b7',
    databaseURL: 'https://wisaga-918b7-default-rtdb.firebaseio.com',
    storageBucket: 'wisaga-918b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz0hQUJEV8FjM0psoyw3Ba6ijiQ74CFWI',
    appId: '1:836056728153:ios:71d01f107d37bf26bd6748',
    messagingSenderId: '836056728153',
    projectId: 'wisaga-918b7',
    databaseURL: 'https://wisaga-918b7-default-rtdb.firebaseio.com',
    storageBucket: 'wisaga-918b7.appspot.com',
    iosBundleId: 'com.example.kantinwisaga1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz0hQUJEV8FjM0psoyw3Ba6ijiQ74CFWI',
    appId: '1:836056728153:ios:71d01f107d37bf26bd6748',
    messagingSenderId: '836056728153',
    projectId: 'wisaga-918b7',
    databaseURL: 'https://wisaga-918b7-default-rtdb.firebaseio.com',
    storageBucket: 'wisaga-918b7.appspot.com',
    iosBundleId: 'com.example.kantinwisaga1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq0TJ9VZR1L4iNRnfeDAzgpDR4GLfXxLg',
    appId: '1:836056728153:web:44bb719ea5e1ed64bd6748',
    messagingSenderId: '836056728153',
    projectId: 'wisaga-918b7',
    authDomain: 'wisaga-918b7.firebaseapp.com',
    databaseURL: 'https://wisaga-918b7-default-rtdb.firebaseio.com',
    storageBucket: 'wisaga-918b7.appspot.com',
    measurementId: 'G-4CB0E1XQ93',
  );
}
